<?php 
	echo $this->doctype();
	$serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
	$config			= $serviceLocator->get('config');
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <?php echo $this->headTitle($this->translate('SITE_NAME'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    </head>
    <body>
    	<?php echo $this->partial('partial/uoe/header-botanical');?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand " href="<?php echo $this->url('home') ?>">
                        <?php echo $this->translate('SITE_NAME') ?>
                    </a>
                </div>
                <?php
                	$this->navigation()->menu()->setPartial(['partial/navigation/uoe-navigation', 'default']);
                	echo $this->navigation('navigation')->menu(); 
                ?>
            </div>
        </nav>
        <hr>
        <?php if (isset($config['global_search']) && $config['global_search']['show_search'] === true) : ?>
        	<div class="row ">
				<?php echo $this->GenericModal('GlobalSearchPleaseWaitModal', 'PLEASE_WAIT', [], 'partial/global-search-results'); ?>
			</div>
		<?php endif; ?>
		
    </body>
</html>
